# ------------------ UBUNTU/DEBIAN TASKS ------------------

- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  become: true

- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    force_apt_get: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Install necessary packages on Debian/Ubuntu
  apt:
    name:
      - nginx
      - openjdk-17-jdk
      - vim
      - wget
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Import the Elasticsearch PGP key on Debian/Ubuntu
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Add the Elasticsearch repository on Debian/Ubuntu
  lineinfile:
    path: /etc/apt/sources.list.d/elastic-8.x.list
    line: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    create: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Install Elasticsearch package on Debian/Ubuntu
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_os_family == "Debian"
  become: true

- name: Ensure Elasticsearch config directory exists
  file:
    path: /etc/elasticsearch
    state: directory
    mode: '0755'
  become: true

- name: Template elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Elasticsearch
  become: true

# ------------------ KIBANA INSTALLATION (Common) ------------------

- name: Install Kibana on Debian/Ubuntu
  apt:
    name: kibana
    state: present
    update_cache: yes
  notify:
    - Start Kibana
    - Enable Kibana
  when: ansible_os_family == "Debian"
  become: true

- name: Ensure Kibana config directory exists
  file:
    path: /etc/kibana
    state: directory
    mode: '0755'
  become: true

- name: Template kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Kibana
  become: true

# ------------------ ENSURE SERVICES RUNNING ------------------

- name: Ensure Elasticsearch service is enabled and running
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  become: true

- name: Ensure Kibana service is enabled and running
  systemd:
    name: kibana
    enabled: yes
    state: started
  become: true
