---
# ------------------ UBUNTU/DEBIAN TASKS ------------------
- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Install necessary packages on Debian/Ubuntu
  apt:
    name:
      - nginx
      - openjdk-17-jdk
      - vim
      - wget
    state: present
  when: ansible_os_family == "Debian"

- name: Import the Elasticsearch PGP key on Debian/Ubuntu
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add the Elasticsearch repository on Debian/Ubuntu
  lineinfile:
    path: /etc/apt/sources.list.d/elastic-8.x.list
    line: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    create: yes
  when: ansible_os_family == "Debian"

- name: Install Elasticsearch package on Debian/Ubuntu
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_os_family == "Debian"

- name: Configure elasticsearch.yml on Debian/Ubuntu
  block:
    - name: Set network.host to 0.0.0.0
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Set http.port to 9200
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port:'
        line: 'http.port: 9200'

    - name: Enable security in elasticsearch.yml
      blockinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        block: |
          xpack.security.enabled: true
          xpack.security.transport.ssl.enabled: true
  when: ansible_os_family == "Debian"

# ------------------ AMAZON LINUX TASKS ------------------
- name: Install dependencies on Amazon Linux
  yum:
    name:
      - java-11-amazon-corretto
      - nginx
      - wget
      - vim
    state: present
  when: ansible_distribution == "Amazon"

- name: Import the Elasticsearch GPG key on Amazon Linux
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == "Amazon"

- name: Add Elasticsearch repo on Amazon Linux manually
  copy:
    dest: /etc/yum.repos.d/elasticsearch.repo
    content: |
      [elasticsearch]
      name=Elasticsearch repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
  when: ansible_distribution == "Amazon"

- name: Install Elasticsearch on Amazon Linux
  yum:
    name: elasticsearch
    state: present
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_distribution == "Amazon"

- name: Configure elasticsearch.yml on Amazon Linux
  block:
    - name: Set network.host to 0.0.0.0
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Set http.port to 9200
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port:'
        line: 'http.port: 9200'

    - name: Enable security in elasticsearch.yml
      blockinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        block: |
          xpack.security.enabled: true
          xpack.security.transport.ssl.enabled: true
  when: ansible_distribution == "Amazon"

# ------------------ KIBANA INSTALLATION (Common) ------------------
- name: Install Kibana on Debian/Ubuntu
  apt:
    name: kibana
    state: present
    update_cache: yes
  notify:
    - Start Kibana
    - Enable Kibana
  when: ansible_os_family == "Debian"

- name: Install Kibana on Amazon Linux
  yum:
    name: kibana
    state: present
  notify:
    - Start Kibana
    - Enable Kibana
  when: ansible_distribution == "Amazon"

- name: Ensure Kibana config directory exists
  file:
    path: /etc/kibana
    state: directory
    mode: '0755'

- name: Template kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Kibana

# ------------------ ENSURE SERVICES RUNNING ------------------
- name: Ensure Elasticsearch service is enabled and running
  systemd:
    name: elasticsearch
    enabled: yes
    state: started

- name: Ensure Kibana service is enabled and running
  systemd:
    name: kibana
    enabled: yes
    state: started
