---
- name: Install base packages (Debian)
  apt:
    name:
      - wget
      - curl
      - apt-transport-https
      - gnupg
      - openjdk-17-jdk
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: elk

- name: Install base packages (RedHat)
  yum:
    name:
      - wget
      - curl
      - unzip
      - java-17-openjdk
    state: present
  when: ansible_os_family == "RedHat"
  tags: elk

- name: Add Elastic GPG key (Debian)
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /usr/share/keyrings/elastic.gpg
    mode: '0644'
  when: ansible_os_family == "Debian"
  tags: elk

- name: Add Elastic repository (Debian)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
  when: ansible_os_family == "Debian"
  tags: elk

- name: Add Elastic repository (RedHat)
  yum_repository:
    name: elastic-7.x
    description: Elasticsearch repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: 1
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: 1
  when: ansible_os_family == "RedHat"
  tags: elk

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: present
  tags: elk

- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reload: yes
  tags: elk

- name: Install Kibana
  package:
    name: kibana
    state: present
  tags: elk

- name: Enable and start Kibana
  systemd:
    name: kibana
    enabled: yes
    state: started
    daemon_reload: yes
  tags: elk