ansible_user: ubuntu
ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/oneclick.pem

ansible_ssh_common_args: >-
  {% if groups['role_Bastion'] is defined and groups['role_Bastion'] | length > 0 %}
  -o ProxyCommand="ssh -i /var/lib/jenkins/.ssh/oneclick.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@{{ hostvars[groups['role_Bastion'][0]].public_ip_address }}"
  {% else %}
  ''
  {% endif %}
