plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

filters:
  tag:Name: asg-instance

keyed_groups:
  - key: tags.Name
    prefix: tag_Name

hostnames:
  - instance_id

compose:
  ansible_host: instance_id

strict: False
