---
- name: Install and Configure Elasticsearch & Kibana
  hosts: tag_monitoring_true
  become: yes
  gather_facts: false   # disable until Python is available

  pre_tasks:
    - name: Ensure Python3 is installed if missing
      raw: |
        if ! command -v python3 &>/dev/null; then
          if [ -f /etc/os-release ] && grep -qi "Amazon Linux" /etc/os-release; then
            yum install -y python3
          elif [ -f /etc/debian_version ]; then
            apt-get update -y && apt-get install -y python3
          fi
        fi
      changed_when: false

    - name: Gather facts after Python installation
      setup:

  roles:
    - role: elk

    

