- name: Ensure apt transport is available
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Elasticsearch GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana APT repository
  ansible.builtin.apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'
    state: present
    filename: 'elastic-8.x'
    update_cache: yes

- name: Install Kibana
  ansible.builtin.apt:
    name: "kibana={{ kibana_version }}"
    state: present
    update_cache: yes
    allow_downgrade: yes

- name: Configure Kibana to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server.host:'
    line: 'server.host: "0.0.0.0"'
    state: present
  notify: restart kibana

- name: Start and enable Kibana service
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: true
